name: pgbackup
director_uuid: REPLACE_WITH_YOUR_DIRECTOR_UUID

instance_groups:
- name: pgbackup
  networks:
  - name: REPLAWE_WITH_YOUR_NETWORK_NAME
    static_ips:
    - 10.250.2.45 # list of ips for pgbackup instances
    cloud_properties:
      security_groups:
      - tf-bosh
      - default
  vm_type: default
  stemcell: trusty
  azs: [z1]
  instances: 1
  jobs:
    - name: pgbackup
      release: pgbackup
  properties:
    pgbackup:
      host: REPLACE_WITH_BOSH_IP_ADRESS
      port: 5432
      username: bosh
      password: REPLAWE_WITH_BOSH_PASSWORD
      schedule:
        hour: '*'
      s3:
        bucket: REPLACE_WITH_YOUR_BUCKET_NAME
        access_key_id: REPLACE_WITH_ACCESS_KEY_ID
        secret_access_key: REPLACE_WITH_SECRET_ACCESS_KEY
        endpoint: REPLACE_WITH_ENDPOINT_WITHOUT_HTTP_OR_HTTPS


update:
  canaries: 1
  canary_watch_time: 1000-60000
  max_in_flight: 1
  serial: false
  update_watch_time: 1000-60000

releases:
- name: pgbackup
  version: latest


stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest
